export const light = {
  title: 'light',

  colors: {
    "base-gradient": "linear-gradient(290deg, rgb(174, 11, 126), rgb(220, 148, 189) 100%);",
    "base-header-blur": "rgba(255, 255, 255, 0.7)",
    "base-white": "#FFFFFF",
    "base-gray": "#131313",
    "base-background": "#FFFFFF",
    "base-background-effect": "rgba(255,255,255, 1)",
    "base-icon": "#000000",
    "base-icon-background": "rgba(245, 245, 245, 0.7)",
    "baseColor": "#F3F2F2",
    "highlightColor": "#c6c5c5",
    "base-card": "#F3F2F2",
    "base-card-secundary": "#e8e8e8",
    "base-card-green": "#e3f3f0",
    "base-card-text-green": "#4bb8a9",
    "base-card-orange": "#fff0da",
    "base-card-text-orange": "#ffa500",
    "base-card-gray": "#d0d0d0",
    "base-card-text-gray": "#4e4e4e",
    "base-card-blue": "#d3e0fa",
    "base-card-text-blue": "#3873e7",
    "base-card-red": "#fcded9",
    "base-card-text-red": "#c53030",
    "base-modal-background": "#ffffff",
    "base-modal-card": "#F3F2F2",
    "base-modal-card-button": "#c6c5c5",
    "base-input": "#EDEDED",
    "base-input-placeholder": "#9d9d9d",
    "base-input-disabled": "#9d9d9d",
    "base-button-text": "#FFFFFF",
    "base-button-primary": "#AE0B7E",
    "base-button-secundary": "#000000",
    "base-button-ternary": "#000000",
    "base-button-disabled": "rgba(240, 240, 240, 0.7)",
    "base-button-hover": "rgba(0, 0, 0, 0.7)",
    "base-button-excursion": "#f5f5f5",
    "button-modal-submit": "#EDEDED",
    "button-modal-button-card": "#EDEDED",
    "base-line-border": "#D9D9D9",
    "base-border": "#E6E5E5",
    "base-border-off": "#D9D9D9",
    "base-border-hover": "#000000",
    "base-border-cart": "#FFFFFF",
    "base-border-input": "#8d8d8d",
    "base-background-cart": "#000000",
    "base-outline": "#9C9C9C",
    "base-hover": "#D7D5D5",
    "base-hover-link": "#000000",
    "base-label": "#a8a8b3",
    "base-text": "#9C9C9C",
    "base-subtitle": "#454545",
    "base-title": "#000000",
    "base-link": "#0070F3",
    "base-link-hover": "#5d86f6",
    "base-link-menu": "#000000",
    "base-error": "#f84747",
    "base-error-secundary": "#c53030",
    "base-error-secundary-bg": "#fcded9",
    "base-failled": "#ffa500",
    "base-hr": "#D9D9D9",
    "base-scrollbar-thumb": "#9C9C9C",
    "brand-pink-dark": "#8f1468",
    "brand-pink": "#AE0B7E",
    "brand-pink-light": "#f5dbe9",
    "brand-yellow-dark": "#C47F17",
    "brand-yellow": "#DBAC2C",
    "brand-yellow-light": "#F1E9C9",
    "brand-orange": "#d17724",
    "brand-orange-dark": "#874f1d",
    "brand-orange-light": "#fde8d9",
    "brand-purple": "#9162c0",
    "brand-purple-dark": "#5f427c",
    "brand-purple-light": "#ede4f5",
    "brand-red": "#c53030",
    "brand-red-dark": "#802622",
    "brand-red-light": "#fcded9",
    "brand-blue": "#0070f3",
    "brand-blue-dark": "#204a9b",
    "brand-blue-light": "#e4e5fe",
    "brand-green": "#04d361",
    "brand-green-dark": "#1e6432",
    "brand-green-light": "#e2f9e4",
  },
  // textSizes: {
  //   "title-title-xl": "3rem",
  //   "title-title-l": "2rem",
  //   "title-title-m": "1.5rem",
  //   "title-title-s": "1.2rem",
  //   "title-title-xs": "1.125rem",
  //   "text-regular-l": "1.25rem",
  //   "text-bold-l": "1.25rem",
  //   "text-regular-m": "1rem",
  //   "text-bold-m": "1rem",
  //   "text-regular-s": "0.875rem",
  //   "text-bold-s": "0.75rem",
  //   "components-tag": "0.625rem",
  //   "components-button-g": "0.875rem",
  //   "components-button-s": "0.75rem",
  // },
  // fonts: {
  //   regular: "'Arial'",
  //   title: "'DM Sans'",
  // },
};
