import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import StyledComponentsRegistry from '@/lib/registry';

// STYLES
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css';

// CONTEXTS
import { CustomThemeProvider } from "@/contexts/theme";

// COMPONENTS
import NavBar from "@/components/NavBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <StyledComponentsRegistry>
        <CustomThemeProvider>
          {/* className={inter.className} */}
          <body>
  
            <NavBar />

            {children}
  
          </body>
        </CustomThemeProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
